version: "3.8"

services:
    mssql:
        container_name: candyshop-mssql
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            ACCEPT_EULA: Y
            MSSQL_SA_PASSWORD: TestTest!23
        ports:
            - 1433:1433
        volumes:
            - mssql:/data/db

volumes:
    mssql:
